// diplomski-vue/src/components/shop/SearchFilterForm.vue
<template>
  <div :class="$style.container">
    <h3>Filter</h3>

    <form @submit.prevent="submitHandler" :class="$style.form">
      <p v-if="error" :class="$style.error">{{ error }}</p>

      <!-- reset i close -->
      <div :class="$style.actions">
        <button @click="resetForm" :class="$style['btn-reset']" type="button">
          Reset filter
        </button>
        <button
          @click="closeHandler"
          :class="$style['btn-cancel']"
          type="button"
        >
          Close filter
        </button>
      </div>

      <!-- include ingredients -->
      <div :class="$style.select">
        <label htmlFor="included-ingredients">Include ingredients:</label>
        <div>
          <select v-model="includeIngredient" id="included-ingredients">
            <option v-for="i in ingredients" :key="i">{{ i.value }}</option>
          </select>
          <button @click="addIngredientToInclude" type="button">Add</button>
          <ingredients-list
            :ingredients="includedIngredients"
            type="INCLUDE"
            @remove-handler="removeIngredientToInclude"
          ></ingredients-list>
        </div>
      </div>

      <!-- exclude ingredients -->
      <div :class="$style.select">
        <label htmlFor="excluded-ingredients">Exclude ingredients:</label>
        <div>
          <select v-model="excludeIngredient" id="excluded-ingredients">
            <option v-for="i in ingredients" :key="i">{{ i.value }}</option>
          </select>
          <button @click="addIngredientToExclude" type="button">Add</button>
          <ingredients-list
            :ingredients="excludedIngredients"
            type="EXCLUDE"
            @remove-handler="removeIngredientToExclude"
          ></ingredients-list>
        </div>
      </div>

      <!-- calories -->
      <div :class="$style.calories">
        <div>
          <label htmlFor="calories-min">Calories min:</label>
          <input
            v-model="caloriesMin"
            type="number"
            id="calories-min"
            :min="0"
            :max="9999"
            :step="1"
            required
          />
        </div>
        <div>
          <label htmlFor="calories-max">Calories max:</label>
          <input
            v-model="caloriesMax"
            type="number"
            id="calories-max"
            :min="1"
            :max="10000"
            :step="1"
            required
          />
        </div>
      </div>
      <!-- diet checks -->
      <div :class="$style.checks">
        <div :class="$style.check">
          <input v-model="isVegetarian" type="checkbox" id="vegetarian" />
          <label htmlFor="vegetarian">Vegetarian</label>
        </div>
        <div :class="$style.check">
          <input v-model="isVegan" type="checkbox" id="vegan" />
          <label htmlFor="vegan">Vegan</label>
        </div>
        <div :class="$style.check">
          <input v-model="isKosher" type="checkbox" id="kosher" />
          <label htmlFor="kosher">Kosher</label>
        </div>
        <div :class="$style.check">
          <input v-model="isLactoseFree" type="checkbox" id="lactose-free" />
          <label htmlFor="lactose-free">Lactose free</label>
        </div>
        <div :class="$style.check">
          <input v-model="isGlutenFree" type="checkbox" id="gluten-free" />
          <label htmlFor="gluten-free">Gluten free</label>
        </div>
      </div>

      <!-- apply -->
      <div :class="$style.actions">
        <button type="submit" :class="$style['btn-apply']">Apply</button>
      </div>
    </form>
  </div>
</template>

<script>
import IngredientsList from '../admin/IngredientsList.vue';

export default {
  emits: ['submitHandler', 'closeHandler'],
  components: { IngredientsList },
  data() {
    return {
      error: null,
      includeIngredient: '',
      includedIngredients: [],
      excludeIngredient: '',
      excludedIngredients: [],
      caloriesMin: 0,
      caloriesMax: 10000,
      isVegetarian: false,
      isVegan: false,
      isKosher: false,
      isLactoseFree: false,
      isGlutenFree: false,
    };
  },
  computed: {
    ingredients() {
      return this.$store.getters['ingredients/ingredients'];
    },
  },
  created() {
    this.loadIngredients();
  },
  methods: {
    async loadIngredients() {
      this.error = null;
      try {
        await this.$store.dispatch('ingredients/loadIngredients');
        if (this.ingredients.length > 0) {
          this.includeIngredient = this.ingredients[0].value;
          this.excludeIngredient = this.ingredients[0].value;
        }
      } catch (e) {
        this.error = e.message;
      }
    },
    addIngredientToInclude() {
      this.error = null;
      if (
        !this.includedIngredients.includes(this.includeIngredient) &&
        !this.excludedIngredients.includes(this.includeIngredient)
      ) {
        this.includedIngredients.push(this.includeIngredient);
      } else {
        this.error = 'Can not add duplicate ingredients.';
      }
    },
    removeIngredientToInclude(item) {
      const index = this.includedIngredients.indexOf(item.value);
      const newList = this.includedIngredients.filter(
        (value, i) => i !== index
      );
      this.includedIngredients = newList;
    },
    addIngredientToExclude() {
      this.error = null;
      if (
        !this.includedIngredients.includes(this.excludeIngredient) &&
        !this.excludedIngredients.includes(this.excludeIngredient)
      ) {
        this.excludedIngredients.push(this.excludeIngredient);
      } else {
        this.error = 'Can not add duplicate ingredients.';
      }
    },
    removeIngredientToExclude(item) {
      const index = this.excludedIngredients.indexOf(item.value);
      const newList = this.excludedIngredients.filter(
        (value, i) => i !== index
      );
      this.excludedIngredients = newList;
    },
    isCalorieRangeValid() {
      this.error = null;
      if (this.caloriesMin >= this.caloriesMax) {
        this.error =
          'Minimum calories can not be larger than maximum calories.';
        return false;
      }
      return true;
    },
    submitHandler() {
      if (this.isCalorieRangeValid()) {
        this.$emit('submitHandler', {
          includedIngredients: this.includedIngredients,
          excludedIngredients: this.excludedIngredients,
          caloriesMin: this.caloriesMin,
          caloriesMax: this.caloriesMax,
          isVegetarian: this.isVegetarian,
          isVegan: this.isVegan,
          isKosher: this.isKosher,
          isLactoseFree: this.isLactoseFree,
          isGlutenFree: this.isGlutenFree,
        });
      }
    },
    closeHandler() {
      this.$emit('closeHandler');
    },
    resetForm() {
      this.error = null;
      this.includeIngredient = this.ingredients[0].value;
      this.excludeIngredient = this.ingredients[0].value;
      this.includedIngredients = [];
      this.excludedIngredients = [];
      this.caloriesMin = 0;
      this.caloriesMax = 10000;
      this.isVegetarian = false;
      this.isVegan = false;
      this.isKosher = false;
      this.isLactoseFree = false;
      this.isGlutenFree = false;
    },
  },
};
</script>

<style module>
.error {
  width: 100%;
  color: var(--color-error-primary);
  background-color: var(--color-error-secondary);
  padding: 4px;
  text-align: center;
  border-radius: 4px;
  border: 1px var(--color-error-primary) solid;
}

.container {
  width: 100%;
  background-color: var(--color-primary-100);
  margin-bottom: 10px;
  padding: 0 1rem;
  border-radius: 5px;
  border: 1px var(--color-primary-400) solid;
}

.container h3 {
  margin-bottom: 0.5rem;
  font-weight: bold;
  font-size: 1.5rem;
  text-decoration: underline;
  margin: 10px 0;
}

.form {
  display: flex;
  flex-direction: column;
}

.form label {
  font-weight: bold;
}

.form input,
.form select {
  font: inherit;
}

.actions {
  display: flex;
  flex-direction: row;
  justify-content: flex-end;
  align-items: center;
  width: 100%;
  margin: 0.5rem 0;
}

.actions button {
  font: inherit;
  font-weight: bold;
  cursor: pointer;
  padding: 0.1rem 1rem;
  border-radius: 4px;
  color: black;
  border: none;
  height: auto;
}

.actions button.btn-apply {
  background-color: var(--color-edit-primary);
}

.actions button.btn-apply:hover {
  background-color: var(--color-edit-secondary);
}

.actions button.btn-reset {
  background-color: var(--color-gray-200);
}

.actions button.btn-reset:hover {
  background-color: var(--color-gray-300);
}

.actions button.btn-cancel {
  background-color: var(--color-delete-primary);
  margin-left: 5px;
}

.actions button.btn-cancel:hover {
  background-color: var(--color-delete-secondary);
  margin-left: 5px;
}

.form select {
  font: inherit;
}

.select {
  margin-bottom: 10px;
  display: flex;
  flex-direction: column;
  flex-wrap: wrap;
  align-items: flex-start;
}

.select select {
  padding: 0.35rem;
}

.select > div > button {
  font: inherit;
  font-weight: bold;
  cursor: pointer;
  padding: 0.2rem 1rem;
  border-radius: 4px;
  background-color: var(--color-gray-300);
  color: black;
  border: none;
  margin-left: 5px;
}

.select > div > button:hover {
  background-color: var(--color-gray-400);
}

.select ul {
  width: 100%;
}

.calories {
  display: flex;
  justify-content: space-around;
}

.calories > div {
  max-width: 10rem;
  min-width: 5rem;
  display: flex;
  flex-direction: column;
}

.checks {
  background-color: white;
  width: fit-content;
  padding: 1rem;
  border-radius: 10px;
  margin: 10px auto;
}

.check {
  display: flex;
  align-items: center;
  margin-bottom: 10px;
}

.check input:hover {
  cursor: pointer;
}

.check input {
  width: 20px;
  height: 20px;
}
</style>

// diplomski-react/src/components/shop/SearchFilterForm.js
import { useCallback, useEffect, useRef, useState } from 'react';
import IngredientList from '../admin/IngredientList';

import classes from './SearchFilterForm.module.css';

const SearchFilterForm = (props) => {
  const apiURL =
    'https://react-http-530b7-default-rtdb.europe-west1.firebasedatabase.app/';

  const [error, setError] = useState(null);
  const includeIngredientInput = useRef();
  const excludeIngredientInput = useRef();

  const caloriesMin = useRef();
  const caloriesMax = useRef();

  const isVegetarianCheckbox = useRef();
  const isVeganCheckbox = useRef();
  const isKosherCheckbox = useRef();
  const isLactoseFreeCheckbox = useRef();
  const isGlutenFreeCheckbox = useRef();

  const [availableIngredients, setAvailableIngredients] = useState([]);
  const [ingredientsToInclude, setIngredientsToInclude] = useState([]);
  const [ingredientsToExclude, setIngredientsToExclude] = useState([]);

  const submitHandler = (event) => {
    event.preventDefault();

    if (isCalorieRangeValid()) {
      const filterOptions = {
        includedIngredients: ingredientsToInclude,
        excludedIngredients: ingredientsToExclude,
        caloriesMin: caloriesMin.current.value,
        caloriesMax: caloriesMax.current.value,
        isVegetarian: isVegetarianCheckbox.current.checked,
        isVegan: isVeganCheckbox.current.checked,
        isKosher: isKosherCheckbox.current.checked,
        isLactoseFree: isLactoseFreeCheckbox.current.checked,
        isGlutenFree: isGlutenFreeCheckbox.current.checked,
      };

      props.onSubmit(filterOptions);
    }
  };

  //get ingredients
  const fetchHandler = useCallback(async () => {
    let apiSuffix = 'ingredients.json';
    try {
      const response = await fetch(apiURL + apiSuffix);

      if (!response.ok) {
        throw new Error('Could not fetch data!');
      }
      const data = await response.json();

      const loadedData = [];

      for (const key in data) {
        loadedData.push(data[key].value);
      }

      loadedData.sort();

      setAvailableIngredients(loadedData);
    } catch (error) {
      setError(error.message);
    }
  }, []);

  useEffect(() => {
    fetchHandler('ingredients');
    fetchHandler('categories');
  }, [fetchHandler]);

  //add ingredient to list
  const addIngredient = (newIngredient, type) => {
    setError(null);
    if (type === 'INCLUDE') {
      if (
        !ingredientsToInclude.includes(newIngredient) &&
        !ingredientsToExclude.includes(newIngredient)
      ) {
        setIngredientsToInclude((prevState) => [...prevState, newIngredient]);
      } else {
        setError('Can not add duplicate ingredients.');
      }
    }
    if (type === 'EXCLUDE') {
      if (
        !ingredientsToInclude.includes(newIngredient) &&
        !ingredientsToExclude.includes(newIngredient)
      ) {
        setIngredientsToExclude((prevState) => [...prevState, newIngredient]);
      } else {
        setError('Can not add duplicate ingredients.');
      }
    }
  };
  //delete ingredient from list
  const deleteIngredient = (value, type) => {
    if (type === 'INCLUDE') {
      const index = ingredientsToInclude.indexOf(value);
      setIngredientsToInclude((prevState) =>
        prevState.filter((value, i) => i !== index)
      );
    }
    if (type === 'EXCLUDE') {
      const index = ingredientsToExclude.indexOf(value);
      setIngredientsToExclude((prevState) =>
        prevState.filter((value, i) => i !== index)
      );
    }
  };

  //check for valid calorie range
  const isCalorieRangeValid = () => {
    setError('');
    if (+caloriesMin.current.value >= +caloriesMax.current.value) {
      setError('Minimum calories can not be larger than maximum calories.');
      return false;
    }
    return true;
  };

  const resetForm = () => {
    setIngredientsToExclude([]);
    setIngredientsToInclude([]);
    caloriesMin.current.value = 0;
    caloriesMax.current.value = 10000;
    isVegetarianCheckbox.current.checked = false;
    isVeganCheckbox.current.checked = false;
    isKosherCheckbox.current.checked = false;
    isLactoseFreeCheckbox.current.checked = false;
    isGlutenFreeCheckbox.current.checked = false;
  };
  return (
    <div className={classes.container}>
      <h3>Filter</h3>
      <form onSubmit={submitHandler} className={classes.form}>
        {error && <p className={classes.error}>{error}</p>}
        <div className={classes.actions}>
          <button
            type="button"
            onClick={resetForm}
            className={classes['btn-reset']}
          >
            Reset filter
          </button>
          <button
            type="button"
            onClick={() => props.onClose(false)}
            className={classes['btn-cancel']}
          >
            Close filter
          </button>
        </div>
        <div className={classes.select}>
          <label htmlFor="included-ingredients">Include ingredients:</label>
          <div>
            <select id="included-ingredients" ref={includeIngredientInput}>
              {availableIngredients.map((value, id) => (
                <option key={id}>{value}</option>
              ))}
            </select>
            <button
              type="button"
              onClick={() => {
                addIngredient(includeIngredientInput.current.value, 'INCLUDE');
              }}
            >
              Add
            </button>
          </div>
          {ingredientsToInclude.length !== 0 && (
            <IngredientList
              ingredients={ingredientsToInclude}
              onDelete={deleteIngredient}
              type="INCLUDE"
            />
          )}
        </div>

        <div className={classes.select}>
          <label htmlFor="excluded-ingredients">Exclude ingredients:</label>
          <div>
            <select id="excluded-ingredients" ref={excludeIngredientInput}>
              {availableIngredients.map((value, id) => (
                <option key={id}>{value}</option>
              ))}
            </select>
            <button
              type="button"
              onClick={() => {
                addIngredient(excludeIngredientInput.current.value, 'EXCLUDE');
              }}
            >
              Add
            </button>
          </div>
          {ingredientsToExclude.length !== 0 && (
            <IngredientList
              ingredients={ingredientsToExclude}
              onDelete={deleteIngredient}
              type="EXCLUDE"
            />
          )}
        </div>
        <div className={classes.calories}>
          <div>
            <label htmlFor="calories">Calories min:</label>
            <input
              ref={caloriesMin}
              type="number"
              id="calories"
              min={0}
              max={9999}
              onChange={isCalorieRangeValid}
              defaultValue={0}
              required
            />
          </div>
          <div>
            <label htmlFor="calories">Calories max:</label>
            <input
              ref={caloriesMax}
              type="number"
              id="calories"
              min={1}
              max={10000}
              onChange={isCalorieRangeValid}
              defaultValue={10000}
              required
            />
          </div>
        </div>
        <div className={classes.checks}>
          <div className={classes.check}>
            <input type="checkbox" id="vegetarian" ref={isVegetarianCheckbox} />
            <label htmlFor="vegetarian">Vegetarian</label>
          </div>
          <div className={classes.check}>
            <input type="checkbox" id="vegan" ref={isVeganCheckbox} />
            <label htmlFor="vegan">Vegan</label>
          </div>
          <div className={classes.check}>
            <input type="checkbox" id="kosher" ref={isKosherCheckbox} />
            <label htmlFor="kosher">Kosher</label>
          </div>
          <div className={classes.check}>
            <input
              type="checkbox"
              id="lactoseFree"
              ref={isLactoseFreeCheckbox}
            />
            <label htmlFor="lactoseFree">Lactose free</label>
          </div>
          <div className={classes.check}>
            <input type="checkbox" id="glutenFree" ref={isGlutenFreeCheckbox} />
            <label htmlFor="glutenFree">Gluten free</label>
          </div>
        </div>

        <div className={classes.actions}>
          <button type="submit" className={classes['btn-apply']}>
            Apply
          </button>
        </div>
      </form>
    </div>
  );
};

export default SearchFilterForm;
