// diplomski-vue/src/pages/shop/ShopPage.vue
<template>
  <div :class="$style.container">
    <h2>Menu</h2>
    <button
      v-if="!filterVisible"
      @click="showFilter"
      :class="$style['btn-filter']"
    >
      Show Filter
    </button>
    <search-filter-form
      v-if="filterVisible"
      @submit-handler="filterMeals"
      @close-handler="hideFilter"
    ></search-filter-form>
    <div :class="$style['sort-selection']">
      <span>
        <strong>Sort by:</strong>
      </span>
      <select v-model="selectedOption">
        <option v-for="option in sortOptions" :key="option">
          {{ option }}
        </option>
      </select>
    </div>
    <meal-list
      v-if="meals.length > 0"
      @like-handler="loadMeals"
      :meals="filteredMeals"
      :isAdmin="false"
    ></meal-list>
    <p v-else :class="$style['not-found']">No meals found.</p>
  </div>
</template>

<script>
import MealList from '@/components/admin/MealList.vue';
import SearchFilterForm from '@/components/shop/SearchFilterForm.vue';
import {
  checkCalorieRange,
  checkDietPreference,
  checkExcludedIngredients,
  checkIncludedIngredients,
  compareByCaloriesAscending,
  compareByCaloriesDescending,
  compareByNameAscending,
  compareByNameDescending,
  compareByPopularityAscending,
  compareByPopularityDescending,
  compareByPriceAscending,
  compareByPriceDescending,
} from '@/helpers/compare-functions';
export default {
  components: { MealList, SearchFilterForm },
  data() {
    return {
      sortOptions: [
        'Name[A-Z]',
        'Name[Z-A]',
        'Price[LOW-HIGH]',
        'Price[HIGH-LOW]',
        'Calories[LOW-HIGH]',
        'Calories[HIGH-LOW]',
        'Popularity[LOW-HIGH]',
        'Popularity[HIGH-LOW]',
      ],
      selectedOption: 'Name[A-Z]',
      filteredMeals: [],
      filterVisible: false,
    };
  },
  computed: {
    meals() {
      return this.$store.getters['meals/meals'];
    },
  },
  created() {
    this.loadMeals();
    this.sortMeals();
  },
  watch: {
    filteredMeals() {
      this.sortMeals();
    },
    selectedOption() {
      this.sortMeals();
    },
  },
  methods: {
    async loadMeals() {
      this.error = null;
      try {
        await this.$store.dispatch('meals/loadMeals');
        this.filteredMeals = this.meals;
      } catch (e) {
        this.error = e.message;
      }
    },
    filterMeals(options) {
      this.filteredMeals = [];
      this.meals.forEach((meal) => {
        if (
          checkIncludedIngredients(
            meal.ingredients,
            options.includedIngredients
          ) &&
          checkExcludedIngredients(
            meal.ingredients,
            options.excludedIngredients
          ) &&
          checkCalorieRange(meal, options.caloriesMin, options.caloriesMax) &&
          checkDietPreference(meal, options)
        ) {
          this.filteredMeals.push(meal);
        }
      });
    },
    sortMeals() {
      switch (this.selectedOption) {
        case 'Name[A-Z]':
          this.filteredMeals.sort(compareByNameAscending);
          break;
        case 'Name[Z-A]':
          this.filteredMeals.sort(compareByNameDescending);
          break;
        case 'Price[LOW-HIGH]':
          this.filteredMeals.sort(compareByPriceAscending);
          break;
        case 'Price[HIGH-LOW]':
          this.filteredMeals.sort(compareByPriceDescending);
          break;
        case 'Calories[LOW-HIGH]':
          this.filteredMeals.sort(compareByCaloriesAscending);
          break;
        case 'Calories[HIGH-LOW]':
          this.filteredMeals.sort(compareByCaloriesDescending);
          break;
        case 'Popularity[LOW-HIGH]':
          this.filteredMeals.sort(compareByPopularityAscending);
          break;
        case 'Popularity[HIGH-LOW]':
          this.filteredMeals.sort(compareByPopularityDescending);
          break;
      }
    },
    showFilter() {
      this.filterVisible = true;
    },
    hideFilter() {
      this.filterVisible = false;
    },
  },
};
</script>

<style module>
.error {
  width: 100%;
  color: var(--color-error-primary);
  background-color: var(--color-error-secondary);
  padding: 4px;
  text-align: center;
  border-radius: 4px;
  border: 1px var(--color-error-primary) solid;
}

.container {
  max-width: 30rem;
  margin: 2rem auto;
  background-color: white;
  padding: 5px 20px;
  box-shadow: 0.3em 0.3em 1em rgba(0, 0, 0, 0.25);
  border-radius: 10px;
  display: flex;
  flex-direction: column;
  align-items: flex-start;
}

.container h2 {
  align-self: center;
  width: 100%;
  font-weight: bold;
  font-size: 2rem;
  text-align: center;
  border-bottom: 2px var(--color-gray-400) solid;
  padding-bottom: 8px;
}
.not-found {
  align-self: center;
  width: 100%;
  font-weight: bold;
  font-size: 1.2rem;
  text-align: center;
}
.btn-filter {
  align-self: flex-end;
  font: inherit;
  font-weight: bold;
  cursor: pointer;
  padding: 0.25rem 1rem;
  border-radius: 4px;
  background-color: var(--color-primary-700);
  color: black;
  border: none;
  margin-bottom: 10px;
}

.btn-filter:hover {
  background-color: var(--color-primary-400);
}

.sort-selection {
  align-self: flex-end;
  margin: 10px 0;
}

.sort-selection select {
  font: inherit;
  padding: 0.35rem;
}

.notification {
  font-size: 1.5rem;
  font-weight: bold;
  align-self: center;
}
</style>

// diplomski-react/src/pages/shop/ShopPage.js
import { useCallback, useEffect, useRef, useState } from 'react';
import MealsList from '../../components/admin/MealsList';
import {
  checkCalorieRange,
  checkDietPreference,
  checkExcludedIngredients,
  checkIncludedIngredients,
  compareByCaloriesAscending,
  compareByCaloriesDescending,
  compareByNameAscending,
  compareByNameDescending,
  compareByPopularityAscending,
  compareByPopularityDescending,
  compareByPriceAscending,
  compareByPriceDescending,
} from '../../helpers/compare-functions';
import SearchFilterForm from '../../components/shop/SearchFilterForm';

import classes from './ShopPage.module.css';

const ShopPage = () => {
  const apiURL =
    'https://react-http-530b7-default-rtdb.europe-west1.firebasedatabase.app/';

  const [error, setError] = useState(null);
  const [meals, setMeals] = useState([]);
  const [options, setOptions] = useState({
    includedIngredients: [],
    excludedIngredients: [],
    caloriesMin: 0,
    caloriesMax: 10000,
    isVegetarian: false,
    isVegan: false,
    isKosher: false,
    isLactoseFree: false,
    isGlutenFree: false,
  });
  const [filterFormVisible, setFilterFormVisible] = useState(false);
  const selectedSort = useRef();

  const sortOptions = [
    'Name[A-Z]',
    'Name[Z-A]',
    'Price[LOW-HIGH]',
    'Price[HIGH-LOW]',
    'Calories[LOW-HIGH]',
    'Calories[HIGH-LOW]',
    'Popularity[LOW-HIGH]',
    'Popularity[HIGH-LOW]',
  ];

  const sortMeals = (meals) => {
    let newMeals = [...meals];
    switch (selectedSort.current.value) {
      case 'Name[A-Z]':
        newMeals.sort(compareByNameAscending);
        break;
      case 'Name[Z-A]':
        newMeals.sort(compareByNameDescending);
        break;
      case 'Price[LOW-HIGH]':
        newMeals.sort(compareByPriceAscending);
        break;
      case 'Price[HIGH-LOW]':
        newMeals.sort(compareByPriceDescending);
        break;
      case 'Calories[LOW-HIGH]':
        newMeals.sort(compareByCaloriesAscending);
        break;
      case 'Calories[HIGH-LOW]':
        newMeals.sort(compareByCaloriesDescending);
        break;
      case 'Popularity[LOW-HIGH]':
        newMeals.sort(compareByPopularityAscending);
        break;
      case 'Popularity[HIGH-LOW]':
        newMeals.sort(compareByPopularityDescending);
        break;
    }
    return newMeals;
    // setMeals(newMeals);
  };

  const filterMeals = useCallback((initialData, options) => {
    let filteredMeals = [];

    initialData.forEach((meal) => {
      if (
        checkIncludedIngredients(
          meal.ingredients,
          options.includedIngredients
        ) &&
        checkExcludedIngredients(
          meal.ingredients,
          options.excludedIngredients
        ) &&
        checkCalorieRange(meal, options.caloriesMin, options.caloriesMax) &&
        checkDietPreference(meal, options)
      ) {
        filteredMeals.push(meal);
      }
    });

    return filteredMeals;
    // setMeals(filteredMeals);
  }, []);

  const updateMeals = useCallback(
    (initialData, options) => {
      setMeals(sortMeals(filterMeals(initialData, options)));
    },
    [filterMeals]
  );

  //fetch items
  const fetchHandler = useCallback(async () => {
    try {
      const response = await fetch(apiURL + 'meals.json');

      if (!response.ok) {
        throw new Error('Could not fetch data!');
      }
      const data = await response.json();

      const loadedMeals = [];

      for (const key in data) {
        loadedMeals.push({
          id: key,
          name: data[key].name,
          category: data[key].category,
          ingredients: data[key].ingredients,
          price: data[key].price,
          calories: data[key].calories,
          isAvailable: data[key].isAvailable,
          isGlutenFree: data[key].isGlutenFree,
          isKosher: data[key].isKosher,
          isLactoseFree: data[key].isLactoseFree,
          isVegan: data[key].isVegan,
          isVegetarian: data[key].isVegetarian,
          numOfLikes: data[key].numOfLikes,
          numOfOrders: data[key].numOfOrders,
        });
      }
      updateMeals(loadedMeals, options);
    } catch (error) {
      setError(error.message);
    }
  }, [updateMeals, options]);

  useEffect(() => {
    fetchHandler();
  }, [fetchHandler]);

  return (
    <div className={classes.container}>
      <h2>MENU</h2>
      {error && <p className={classes.error}>{error}</p>}
      {!filterFormVisible && (
        <button
          onClick={() => setFilterFormVisible(true)}
          className={classes['btn-filter']}
        >
          Show filter
        </button>
      )}
      {filterFormVisible && (
        <SearchFilterForm
          onSubmit={setOptions}
          onClose={setFilterFormVisible}
        />
      )}
      <div className={classes['sort-selection']}>
        <span>
          <strong>Sort by: </strong>
        </span>
        <select ref={selectedSort} onChange={fetchHandler}>
          {sortOptions.map((value, index) => (
            <option key={index}>{value}</option>
          ))}
        </select>
      </div>
      {meals.length > 0 ? (
        <MealsList isAdmin={false} items={meals} updateItems={fetchHandler} />
      ) : (
        <p className={classes.notification}>No meals found</p>
      )}
    </div>
  );
};

export default ShopPage;
