// diplomski-react/src/pages/shop/CartPage.js
import { useContext, useState } from 'react';
import { CartContext } from '../../context/cart-context';
import { Link, useNavigate } from 'react-router-dom';

import classes from './CartPage.module.css';

const CartPage = () => {
  const apiURL =
    'https://react-http-530b7-default-rtdb.europe-west1.firebasedatabase.app/';

  const { cartItems, addToCart, removeFromCart, clearCart, getCartTotal } =
    useContext(CartContext);
  const [error, setError] = useState(null);

  const navigate = useNavigate();

  const updateNumOfOrders = async (meal, increment) => {
    setError(null);
    let url = apiURL + 'meals/' + meal.id + '.json';

    try {
      const response = await fetch(url, {
        method: 'PATCH',
        body: JSON.stringify({
          ...meal,
          numOfOrders: meal.numOfOrders + increment,
        }),
        headers: {
          'Content-type': 'application/json',
        },
      });

      if (!response.ok) {
        throw new Error('Could not save data!');
      }
    } catch (error) {
      setError(error.message);
    }
  };

  const orderHandler = () => {
    setError(null);
    if (cartItems.length <= 0) {
      setError('Please add items to cart');
    } else {
      var result = window.confirm('Are you sure you want to order?');
      if (result) {
        cartItems.forEach((item) => {
          let validItem = { ...item };
          delete validItem.quantity;
          console.log(item);
          updateNumOfOrders(validItem, item.quantity);
        });
        clearCart();
        navigate('/shop');
      }
    }
  };

  return (
    <div className={classes.container}>
      <h2>Cart</h2>
      {error && <p className={classes.error}>{error}</p>}
      <div className={classes.actions}>
        <Link to={'..'}>Back</Link>
        <button onClick={clearCart} className={classes['btn-reset']}>
          Clear cart
        </button>
      </div>
      <div className={classes.items}>
        {cartItems.length > 0 ? (
          cartItems.map((item, index) => (
            <div key={index} className={classes.item}>
              <div className={classes.info}>
                <h3>{item.name}</h3>
                <p>(${item.price})</p>
              </div>
              <div className={classes['cart-controls']}>
                <button
                  onClick={() => {
                    removeFromCart(item);
                  }}
                >
                  -
                </button>
                <span>{cartItems.find((i) => i.id === item.id).quantity}</span>
                <button
                  onClick={() => {
                    addToCart(item);
                  }}
                >
                  +
                </button>
              </div>
            </div>
          ))
        ) : (
          <h3 className={classes.item}>Cart is empty</h3>
        )}
      </div>
      <div className={classes.price}>
        <strong>Total: </strong>${getCartTotal()}
      </div>
      <div className={classes.apply}>
        <button onClick={orderHandler} className={classes['btn-apply']}>
          Order
        </button>
      </div>
    </div>
  );
};

export default CartPage;

// diplomski-vue/src/pages/shop/CartPage.vue
<template>
  <div :class="$style.container">
    <h2>Cart</h2>
    <p v-if="error" :class="$style.error">{{ error }}</p>
    <div :class="$style.actions">
      <router-link to="/shop">Back</router-link>
      <button @click="clearCart" :class="$style['btn-reset']">
        Clear cart
      </button>
    </div>

    <div v-if="cart.length > 0" :class="$style.items">
      <div v-for="item in cart" :key="item.name" :class="$style.item">
        <div :class="$style.info">
          <h3>{{ item.name }}</h3>
          <p>(${{ item.price }})</p>
        </div>
        <div :class="$style['cart-controls']">
          <button @click="removeFromCart(item)">-</button>
          <span>{{ item.quantity }}</span>
          <button @click="addToCart(item)">+</button>
        </div>
      </div>
    </div>

    <div v-else :class="$style.items">
      <h3 :class="$style.item">Cart is empty</h3>
    </div>

    <div :class="$style.price"><strong>Total: </strong>${{ cartTotal }}</div>
    <div :class="$style.apply">
      <button @click="submitHandler" :class="$style['btn-apply']">Order</button>
    </div>
  </div>
</template>

<script>
import { mapActions, mapGetters } from 'vuex';

export default {
  data() {
    return {
      error: null,
    };
  },
  computed: {
    ...mapGetters({
      cart: 'cart/cart',
      cartTotal: 'cart/cartTotal',
      getItem: 'cart/getItem',
    }),
  },
  methods: {
    ...mapActions({
      addToCart: 'cart/addToCart',
      removeFromCart: 'cart/removeFromCart',
      clearCart: 'cart/clearCart',
    }),
    submitHandler() {
      if (this.cart.length <= 0) {
        this.error = 'Please add items to cart';
      } else {
        var result = window.confirm('Are you sure you want to order?');
        if (result) {
          this.cart.forEach((item) => {
            let validItem = { ...item };
            delete validItem.quantity;
            const newItem = {
              ...validItem,
              numOfOrders: validItem.numOfOrders + item.quantity,
            };
            this.updateMealOrders(newItem);
          });
          this.clearCart();
          this.$router.push('/shop');
        }
      }
    },
    async updateMealOrders(meal) {
      this.error = null;
     
      try {
        await this.$store.dispatch('meals/updateMealOrders', {
          ...meal,
        });
      } catch (e) {
        this.error = e.message;
      }
    },
  },
};
</script>

<style module>
.error {
  width: 100%;
  color: var(--color-error-primary);
  background-color: var(--color-error-secondary);
  padding: 4px;
  text-align: center;
  border-radius: 4px;
  border: 1px var(--color-error-primary) solid;
}

.container {
  max-width: 30rem;
  margin: 2rem auto;
  background-color: white;
  padding: 5px 20px;
  box-shadow: 0.3em 0.3em 1em rgba(0, 0, 0, 0.25);
  border-radius: 10px;
  display: flex;
  flex-direction: column;
  align-items: flex-start;
}

.container h2 {
  align-self: center;
  width: 100%;
  font-weight: bold;
  font-size: 2rem;
  text-align: center;
  border-bottom: 2px var(--color-gray-400) solid;
  padding-bottom: 8px;
}

.actions {
  display: flex;
  flex-direction: row;
  justify-content: space-between;
  align-items: center;
  width: 100%;
  margin: 0.5rem 0;
}

.actions button {
  font: inherit;
  font-weight: bold;
  cursor: pointer;
  padding: 0.1rem 1rem;
  border-radius: 4px;
  color: black;
  border: none;
  height: auto;
}

.actions a {
  text-decoration: underline;
  font-weight: bold;
  padding: 2px 10px;
  border-radius: 10px;
  color: var(--color-error-primary);
}

.actions a:hover {
  text-decoration: none;
  background-color: var(--color-error-secondary);
}

.actions button.btn-reset {
  background-color: var(--color-primary-700);
}

.actions button.btn-reset:hover {
  background-color: var(--color-primary-400);
}

.apply {
  display: flex;
  flex-direction: row;
  justify-content: flex-end;
  align-items: center;
  width: 100%;
  margin: 0.5rem 0;
}

.apply button.btn-apply {
  font: inherit;
  font-weight: bold;
  cursor: pointer;
  padding: 0.1rem 1rem;
  border-radius: 4px;
  color: black;
  border: none;
  height: auto;
  background-color: var(--color-edit-primary);
}

.apply button.btn-apply:hover {
  background-color: var(--color-edit-secondary);
}

.price {
  display: flex;
  flex-direction: row;
  justify-content: flex-end;
  align-items: center;
  width: 100%;
  margin: 10px 0 0 0;
}

.items {
  width: 100%;
}

.item {
  display: flex;
  flex-direction: row;
  justify-content: space-between;
  align-items: center;
  flex-wrap: wrap;
  background-color: var(--color-primary-300);
  margin-bottom: 10px;
  padding: 1rem;
  border-radius: 5px;
  border: 2px var(--color-primary-600) solid;
}

.info h3,
.info p {
  font-size: 1.2rem;
  margin: 0;
}

.cart-controls button {
  font: inherit;
  font-weight: bold;
  cursor: pointer;
  padding: 0.2rem 1rem;
  border-radius: 4px;
  background-color: var(--color-gray-300);
  color: black;
  border: none;
}

.cart-controls button:hover {
  background-color: var(--color-gray-400);
}

.cart-controls span {
  font-weight: bold;
  background-color: white;
  padding: 0.2rem 0.5rem;
  margin: 0 5px;
}
</style>
