// diplomski-vue/src/pages/admin/MealsPage.vue
<template>
  <div :class="$style.container">
    <h2>Meals</h2>
    <p v-if="error" :class="$style.error">{{ error }}</p>
    <button
      v-if="!addFormVisible"
      :class="$style['btn-add']"
      @click="showAddForm"
    >
      + Add
    </button>
    <meal-form
      v-if="addFormVisible"
      @submit-handler="addMeal"
      @closeHandler="hideAddForm"
      method="Add"
    ></meal-form>
    <meal-form
      v-if="editFormVisible"
      @submit-handler="editMeal"
      @closeHandler="hideEditForm"
      method="Edit"
      :meal="mealForEdit"
    ></meal-form>
    <meal-list
      v-if="meals.length > 0"
      @edit-handler="updateEditForm"
      @delete-handler="deleteMeal"
      @availability-handler="changeAvailability"
      :meals="meals"
      :isAdmin="true"
      :isLoading="isLoading"
    ></meal-list>
    <p v-else :class="$style['not-found']">No meals found.</p>
  </div>
</template>

<script>
import { mapActions } from 'vuex';
import MealForm from '../../components/admin/MealForm.vue';
import MealList from '../../components/admin/MealList.vue';

export default {
  components: {
    MealForm,
    MealList,
  },
  data() {
    return {
      error: null,
      mealForEdit: {},
      addFormVisible: false,
      editFormVisible: false,
      isLoading: false,
    };
  },
  computed: {
    ...mapActions({
      updateMealOrders: 'meals/updateMealOrders',
    }),
    meals() {
      return this.$store.getters['meals/meals'];
    },
  },
  created() {
    this.loadMeals();
  },
  methods: {
    async loadMeals() {
      this.error = null;
      try {
        await this.$store.dispatch('meals/loadMeals');
      } catch (e) {
        this.error = e.message;
      }
    },
    async addMeal(meal) {
      this.error = null;
      const randOrders = Math.floor(Math.random() * (200 - 50) + 20);
      const randLikes = Math.floor(Math.random() * (50 - 5) + 5);
      try {
        await this.$store.dispatch('meals/addMeal', {
          name: meal.name,
          category: meal.category,
          ingredients: meal.ingredients,
          price: meal.price,
          calories: meal.calories,
          isVegetarian: meal.isVegetarian,
          isVegan: meal.isVegan,
          isKosher: meal.isKosher,
          isLactoseFree: meal.isLactoseFree,
          isGlutenFree: meal.isGlutenFree,
          numOfOrders: randOrders,
          numOfLikes: randLikes,
          isAvailable: true,
        });
        this.loadMeals();
        this.hideAddForm();
      } catch (e) {
        this.error = e.message;
      }
    },
    async editMeal(meal) {
      this.error = null;
      try {
        await this.$store.dispatch('meals/editMeal', {
          id: meal.id,
          name: meal.name,
          category: meal.category,
          ingredients: meal.ingredients,
          price: meal.price,
          calories: meal.calories,
          isVegetarian: meal.isVegetarian,
          isVegan: meal.isVegan,
          isKosher: meal.isKosher,
          isLactoseFree: meal.isLactoseFree,
          isGlutenFree: meal.isGlutenFree,
        });
        this.loadMeals();
        this.hideEditForm();
      } catch (e) {
        this.error = e.message;
      }
    },
    updateEditForm(newMeal) {
      this.mealForEdit = newMeal;
      this.showEditForm();
    },
    async deleteMeal(meal) {
      this.error = null;
      var result = window.confirm('Want to delete?');
      if (result) {
        try {
          await this.$store.dispatch('meals/deleteMeal', {
            id: meal.id,
          });
          this.loadMeals();
          this.hideAddForm();
          this.hideEditForm();
        } catch (e) {
          this.error = e.message;
        }
      }
    },
    showAddForm() {
      this.addFormVisible = true;
      this.editFormVisible = false;
    },
    hideAddForm() {
      this.addFormVisible = false;
    },
    showEditForm() {
      this.editFormVisible = true;
      this.addFormVisible = false;
    },
    hideEditForm() {
      this.editFormVisible = false;
    },
    async changeAvailability() {
      this.loadMeals();
    },
  },
};
</script>

<style module>
.error {
  width: 100%;
  color: var(--color-error-primary);
  background-color: var(--color-error-secondary);
  padding: 4px;
  text-align: center;
  border-radius: 4px;
  border: 1px var(--color-error-primary) solid;
}

.container {
  max-width: 30rem;
  margin: 2rem auto;
  background-color: white;
  padding: 5px 20px;
  box-shadow: 0.3em 0.3em 1em rgba(0, 0, 0, 0.25);
  border-radius: 10px;
  display: flex;
  flex-direction: column;
  align-items: flex-start;
}

.container h2 {
  align-self: center;
  width: 100%;
  font-weight: bold;
  font-size: 2rem;
  text-align: center;
  border-bottom: 2px var(--color-gray-400) solid;
  padding-bottom: 8px;
}
.not-found {
  align-self: center;
  width: 100%;
  font-weight: bold;
  font-size: 1.2rem;
  text-align: center;
}

.btn-add {
  align-self: flex-end;
  font: inherit;
  font-weight: bold;
  cursor: pointer;
  padding: 0.25rem 1rem;
  border-radius: 4px;
  background-color: var(--color-primary-700);
  color: black;
  border: none;
  margin-bottom: 10px;
}

.btn-add:hover {
  background-color: var(--color-primary-400);
}

.notification {
  font-size: 1.5rem;
  font-weight: bold;
  align-self: center;
}
</style>

// diplomski-react/src/pages/admin/MealsPage.js
import { useCallback, useEffect, useState } from 'react';
import MealForm from '../../components/admin/MealForm';
import MealsList from '../../components/admin/MealsList';
import { compareByNameAscending } from '../../helpers/compare-functions';

import classes from './MealsPage.module.css';

const MealsPage = () => {
  const apiURL =
    'https://react-http-530b7-default-rtdb.europe-west1.firebasedatabase.app/';

  const [error, setError] = useState(null);
  const [addFormVisible, setAddFormVisible] = useState(false);
  const [editFormVisible, setEditFormVisible] = useState(false);

  const [meals, setMeals] = useState([]);
  const [mealForEdit, setMealForEdit] = useState();

  const showAddForm = () => {
    setError(null);
    setAddFormVisible(true);
    setEditFormVisible(false);
  };

  const hideAddForm = () => {
    setError(null);
    setAddFormVisible(false);
  };

  const showEditForm = () => {
    setError(null);
    setEditFormVisible(true);
    setAddFormVisible(false);
  };

  const hideEditForm = () => {
    setError(null);
    setEditFormVisible(false);
  };

  //fetch items
  const fetchHandler = useCallback(async () => {
    setError(null);
    try {
      const response = await fetch(apiURL + 'meals.json');

      if (!response.ok) {
        throw new Error('Could not fetch data!');
      }
      const data = await response.json();

      const loadedMeals = [];

      for (const key in data) {
        loadedMeals.push({
          id: key,
          name: data[key].name,
          category: data[key].category,
          ingredients: data[key].ingredients,
          price: data[key].price,
          calories: data[key].calories,
          isAvailable: data[key].isAvailable,
          isGlutenFree: data[key].isGlutenFree,
          isKosher: data[key].isKosher,
          isLactoseFree: data[key].isLactoseFree,
          isVegan: data[key].isVegan,
          isVegetarian: data[key].isVegetarian,
          numOfLikes: data[key].numOfLikes,
          numOfOrders: data[key].numOfOrders,
        });
      }
      loadedMeals.sort(compareByNameAscending);
      setMeals(loadedMeals);
    } catch (error) {
      setError(error.message);
    }
  }, []);

  useEffect(() => {
    fetchHandler();
  }, [fetchHandler]);

  //add item
  const addHandler = async (meal, method) => {
    setError(null);
    if (method === 'POST' && meals.some((e) => e.name === meal.name)) {
      setError('Meal already exists');
    } else {
      let url = apiURL + 'meals.json';
      if (method === 'PATCH') {
        url = apiURL + 'meals/' + meal.id + '.json';
      }
      try {
        const response = await fetch(url, {
          method: method,
          body: JSON.stringify(meal),
          headers: {
            'Content-type': 'application/json',
          },
        });

        if (!response.ok) {
          throw new Error('Could not save data!');
        }

        fetchHandler();
        if (method === 'POST') {
          hideAddForm();
        }
        if (method === 'PATCH') {
          hideEditForm();
        }
      } catch (error) {
        setError(error.message);
      }
    }
  };

  //delete item
  const deleteHandler = async (id) => {
    var result = window.confirm('Want to delete?');
    if (result) {
      setError(null);

      try {
        const response = await fetch(apiURL + 'meals/' + id + '.json', {
          method: 'DELETE',
          headers: {
            'Content-Type': 'application/json',
          },
        });

        if (!response.ok) {
          throw new Error('Could not delete data!');
        }

        fetchHandler();
      } catch (error) {
        setError(error.message);
      }
    }
  };

  const setUpEditForm = (meal) => {
    setMealForEdit(meal);
    showEditForm();
  };

  return (
    <div className={classes.container}>
      <h2>Meals</h2>
      {error && <p className={classes.error}>{error}</p>}

      {!addFormVisible && (
        <button onClick={showAddForm} className={classes['btn-add']}>
          + Add
        </button>
      )}

      {addFormVisible && (
        <MealForm
          method={'POST'}
          onSubmit={addHandler}
          onCancel={hideAddForm}
        />
      )}

      {editFormVisible && (
        <MealForm
          method={'PATCH'}
          onSubmit={addHandler}
          meal={mealForEdit}
          onCancel={hideEditForm}
        />
      )}

      {meals.length > 0 ? (
        <MealsList
          isAdmin={true}
          items={meals}
          onDelete={deleteHandler}
          onEdit={setUpEditForm}
          onChangeAvailabiliy={addHandler}
        />
      ) : (
        <p>No meals found.</p>
      )}
    </div>
  );
};

export default MealsPage;
